# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c7c14152d60ad1288511b2e5c2af88435ed53008bd4d7b20a6fdc8b62b2d947e6ec232b02709c97e074ddf75f7954ee0860a7ef4143291bdfb5ea278034f855

test:
  secret_key_base: 05f49ddc048794f03fcb5ecad866e63fe46c7ae71a995b63358efdb375c1a33298cea35b172fbcb6f361609a0d7098f4b5d33d695a3427e614c55ec59f02bc14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
